### ISSUE TITLE
Code block has multiple scroll bars

### ISSUE THREAD

**Issue by budui** [onweru/newsroom#1]
nice theme!

but the code blocks have multiple scroll bars:
* screenshot from <https://rooms.netlify.com/post/creating-a-new-theme/>*

![image](https://user-images.githubusercontent.com/16448529/64472458-5bac6a80-d191-11e9-9380-33915886f8fc.png)
Google Chrome: Version 76.0.3809.132 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/16448529/64472503-150b4000-d192-11e9-83d2-dec66020b6d3.png)
firefox-developer-edition-69.0b16-1

but it looks good in Google Chrome Android (Chrome 76.0.3809.132):
![220751914](https://user-images.githubusercontent.com/16448529/64472553-b7c3be80-d192-11e9-9087-aca2aa80d9ef.jpg)

**Comment by onweru** [comment]
@budui , thank you a lot for bringing this to my attention.

**Comment by budui** [comment]
![image](https://user-images.githubusercontent.com/16448529/64472833-d035d800-d196-11e9-8783-8e188d28950b.png)

**Comment by budui** [comment]
OS: Manjaro Linux x86_64
Host: Vostro 3668
Kernel: 4.19.66-1-MANJARO
Uptime: 16 days, 8 hours, 26 mins
Packages: 1226 (pacman)
Shell: zsh 5.7.1
Resolution: 1920x1080
DE: Xfce
WM: Xfwm4
WM Theme: Adapta-Maia
Theme: Adapta-Eta-Maia [GTK2], Adwaita [GTK3]
Icons: Papirus-Maia [GTK2], Adwaita [GTK3]
                               Terminal: alacritty
                               CPU: Intel i5-7400 (4) @ 3.500GHz
                               GPU: NVIDIA GeForce GTX 745
                               GPU: Intel HD Graphics 630
                               Memory: 6248MiB / 7884MiB

**Comment by budui** [comment]
May be it 's hard for you to reproduce the bug with Mac and manjaro, I opened this page again using Windows Edge. (Windows 10)
![615669369](https://user-images.githubusercontent.com/16448529/64473153-5868ad00-d198-11e9-9afe-a1da210004d3.jpg)
![255744702](https://user-images.githubusercontent.com/16448529/64473154-5b639d80-d198-11e9-9dab-fe6b4daf9a5b.jpg)

**Comment by onweru** [comment]
I will have a look at it and try a fix.

**Comment by rikusen0335** [comment]
I'm on Windows10 and `Hugo Static Site Generator v0.58.3-4AAC02D4`, but the code block seems working correctly!

**Comment by onweru** [comment]
Awesome.
