### ISSUE TITLE
Removing the 'year' span from the footer breaks then menu pop-down etc

### ISSUE THREAD

**Issue by mikebway** [onweru/newsroom#10]
Preferring to have the copyright years in the source, I replaced `<span class = 'year'></span>` in my clone of the footer.html partial. This broke the JavaScript-driven menu (amongst other things) because the `updateDate()` function in index.js assumed the presences of a span class of `year` and threw an exception.

For me, the fix was to modify the `updateDate()` function as follows.

```
(function updateDate() {
  var dateElem = elem('.year')
  if (dateElem) {
    var date = new Date();
    var year = date.getFullYear();
    dateElem.innerHTML = year;
  }
})();
```

**Comment by onweru** [comment]
@mikebway, thanks for raising this. Awesome

**Comment by mikebway** [comment]
@onweru - Thanks to you for doing all the hard work creating the theme! I'll let you know when my site goes live.

**Comment by mikebway** [comment]
FYI - [mikebroadway.com](mikebroadway.com) is now live. The About page acknowledges the Newsroom theme. Much more content to add but the hard work of getting the site framework and photo gallery display in place is done.
