### ISSUE TITLE
When this theme will be finish?

### ISSUE THREAD

**Issue by Abdulsametileri** [onweru/newsroom#11]
First of all, thank you for this great theme. Previously I was used hugo-swift-theme. It was really good choice for me. I am very pleased. You're really good developer :)

I really want to use this theme in my own project. But I guess this theme hasnt finished yet. Is there any plan to finish your work?

**Comment by onweru** [comment]
@Abdulsametileri,

I’m glad you find the themes helpful. Umh, I wanted to keep this theme very simple. In your view, what do you think is missing?

**Comment by Abdulsametileri** [comment]
https://rooms.netlify.com/ in this demo site

It seems Toogle dark mode are not working, nothings changes when I change the switch

in this https://rooms.netlify.com/post/ Clicking page 2. Redirects to https://post/page/2/ as you know, this url is broken. 

And I saw your master branch commits last 2 days.
I was guessed you have had unfinished business :) 

This is what I am asking

**Comment by onweru** [comment]
Umh, steps to reproduce?

1. Browser?
2. OS?

On all the devices (macOS & iOS, on all main browsers) I have tested in, I'm unable to reproduce what you just described. Everything works well. 

Please note that all features may not work on all browsers.

> And I saw your master branch has some commits last 2 days.
I was guessed you have had unfinished business :)

I make routine bug fixes and updates, when my schedule allows.

**Comment by Abdulsametileri** [comment]
1. Google Chrome 
Version 79.0.3945.88 (Official Build) (64-bit)
2. MacOS 
Mojave 10.14.6

# Redirection Problem
![Screen Shot 2020-01-02 at 4 23 49 PM](https://user-images.githubusercontent.com/19360039/71669039-7035f380-2d7c-11ea-8826-10fbb9256824.png)

#Toogle Dark Mode

![Screen Shot 2020-01-02 at 4 24 46 PM](https://user-images.githubusercontent.com/19360039/71669040-70ce8a00-2d7c-11ea-982b-b998228053b9.png)

**Comment by onweru** [comment]
Weird, have you attempted testing elsewhere? Say like using your phone. Thanks for letting me know that dark mode doesn't work on Mojave. I'm on Catalina and everything works well.

> in this https://rooms.netlify.com/post/ Clicking page 2. Redirects to https://post/page/2/ as you know, this url is broken

This was because I hadn't set the baseURL in my config.toml. Resolved

**Comment by Abdulsametileri** [comment]
I have Huawei Y6. Im using chrome too. Toogle Dark Mode still does not working .

>This was because I hadn't set the baseURL in my config.toml. Resolved
Thats Great.
