### ISSUE TITLE
there will be some problems when I set 'image' to another site url in the front matter.

### ISSUE THREAD

**Issue by jsyt** [onweru/newsroom#13]
This is a nice theme, I really like it.
But there will be some problems when I set 'image' to another site url in the front matter.
E.g. written below:
> author: Michael Henderson
> date: 2019-02-28
> title: Creating a New Theme
> image: https://img-1256541035.cos.ap-shanghai.myqcloud.com/imgs/gohugo-default-sample-hero-image.jpg

And then the image doesn't show up. 

I know the URL is incorrect. I have modified the code.

[/layouts/index.html](https://github.com/jsyt/newsroom/blob/1909c68b471f15a1355e0b138d5c728901ffcc05/layouts/index.html#L13-L20)
[/layouts/_default/single.html](https://github.com/jsyt/newsroom/blob/1909c68b471f15a1355e0b138d5c728901ffcc05/layouts/_default/single.html#L9-L16)

But it is only work in the `hugo serve` mode, it is not work in the `hugo` mode.  I don't know why, maybe it is environment problem or some thing else. 
I just learned about hugo, I don't know much about it yet.

Thanks!

**Comment by onweru** [comment]
@jsyt,

Currently, external paths (URLs) are not supported for the featured image i.e the image from the front matter. The assumption is that you'll self-host these images. 

Perhaps, I'll consider accomodating external paths.

**Comment by jsyt** [comment]
I have fixed this problem, the reason why the picture is not displayed properly in the `hugo` mode is that there is still an image url not change in the '/layouts/partials/opengraph.html'.
