### ISSUE TITLE
Paginate not working

### ISSUE THREAD

**Issue by anistark** [onweru/newsroom#14]
Simply added this theme and copied the `config.toml` from `/exampleSite/config.toml`

Getting this error:
```
ERROR 2020/05/06 20:44:01 Error while rendering "home" in "": template: index.html:4:15: executing "main" at <.Paginate>: error calling Paginate: a Paginator was previously built for this Node without filters; look for earlier .Paginator usage
```

Anybody else faced this or know how to fix it?

**Comment by onweru** [comment]
@anistark,

Could I have a look at your setup?

**Comment by anistark** [comment]
MacOS Sierra 10.12.6

> hugo version
`Hugo Static Site Generator v0.48/extended darwin/amd64 BuildDate: unknown`

@onweru What other setup needed?

I just ran : `git submodule add https://github.com/onweru/newsroom.git themes/newsroom`

And here's the `config.toml`:

```
baseURL = "/"
title = "Ani"
theme = "newsroom"
author = "Ani"
canonifyurls = true
paginate = 5

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]
  twitter = "kranirudha"
```

**Comment by onweru** [comment]
> MacOS Sierra 10.12.6
> 
> > hugo version
> > `Hugo Static Site Generator v0.48/extended darwin/amd64 BuildDate: unknown`
> 
> @onweru What other setup needed?
> 
> I just ran : `git submodule add https://github.com/onweru/newsroom.git themes/newsroom`
> 
> And here's the `config.toml`:
> 
> ```
> baseURL = "/"
> title = "Ani"
> theme = "newsroom"
> author = "Ani"
> canonifyurls = true
> paginate = 5
> 
> pygmentsCodefences = true
> pygmentsCodefencesGuessSyntax = true
> pygmentsUseClasses=true
> pygmentsOptions = "linenos=table"
> 
> [params]
>   twitter = "kranirudha"
> ```

@anistark ,  

Firstly, thanks for this 👆 information.

Could you try updating your Hugo installation and let me know if the error persists?

My bad, I have indicated that the minimum version required to run this theme is `0.42` in my theme.toml file. There have been a couple of breaking changes since that version.

**Comment by anistark** [comment]
@onweru Thanks. That worked.

> hugo version
```Hugo Static Site Generator v0.70.0/extended darwin/amd64 BuildDate: unknown```
