### ISSUE TITLE
Deeplinks glitch maybe?

### ISSUE THREAD

**Issue by iranvir** [onweru/newsroom#15]
Hello, One! 
I am still at the early stages of designing my site around your theme, but I have run into an issue with deep links.
The first run of the link works fine, for example, if http://localhost:1313/page#heading1 works fine.
But if someone follows that link then hovers over something else like Heading2, the link shows up as:

http://localhost:1313/page#heading1#heading2

Am I missing something? I am trying to import only necessary parts from the repo, like assets and layouts directory. If I have missed something please let me know :)

Lastly, thank you for this theme. I absolutely love it!!

**Comment by onweru** [comment]
@sranvir 
> Lastly, thank you for this theme. I absolutely love it!!

You're most welcome.

I have observed that the problem you described only occurs locally i.e while you're using the local server. So things should be cool once you deploy.

**Comment by sranvir** [comment]
I thought so, I checked your blog and tried to reproduce the bug but it didn't work.
Noticed a couple of other glitches in paths as well (in local server, of course) will let you know if I find any fix.
