### ISSUE TITLE
Error at build

### ISSUE THREAD

**Issue by luseloso** [onweru/newsroom#17]
I am getting the following error

Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_65b0252c4a2fb050308e79c52b2c1909" not found in file cache

**Comment by luseloso** [comment]
Hugo Static Site Generator v0.71.0-06150C87 linux/amd64 BuildDate: 2020-05-18T16:08:02Z

**Comment by onweru** [comment]
@luseloso, ensure you're using the extended version of hugo [like advised in the readme](https://github.com/onweru/newsroom#installation).

In you're case that would be either 1 or 2 below 👇 

1. https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_extended_0.71.0_Linux-64bit.tar.gz
2. https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_extended_0.71.0_Linux-64bit.deb

These links are always updated on the [hugo releases' page](https://github.com/gohugoio/hugo/releases)

**Comment by luseloso** [comment]
i have the latest version

**Comment by onweru** [comment]
@luseloso,

> Hugo Static Site Generator v0.71.0-06150C87 linux/amd64 BuildDate: 2020-05-18T16:08:02Z

It seems that you have the latest version of the `non-extended version` of hugo.

> i have the latest version

You need the latest `extended version` which can be found via the links I shared earlier.

**Comment by luseloso** [comment]
got it
