### ISSUE TITLE
Is this avaliable with Disqus?

### ISSUE THREAD

**Issue by rikusen0335** [onweru/newsroom#2]

**Comment by onweru** [comment]
@rikusen0335, 

No, this theme doesn't have Disqus functionality enabled. If that's something you would like to have, Hugo makes it's somewhat easy, [here is a link on the docs](https://gohugo.io/templates/internal/#configure-disqus).

I could add that functionality when I free. Is that something you would like to have?

**Comment by rikusen0335** [comment]
Thank you for answering, and yes, that's something I'd like to have all of SSGs.

Well then I may be able to add it my self, thanks!

**Comment by onweru** [comment]
Thanks for sharing the idea. I'll add it sometimes this week; it may need a lit bit of attention so that it can adapt to `dark mode` too.

**Comment by rikusen0335** [comment]
Yes! I'll be waiting or maybe do PR!

**Comment by onweru** [comment]
@rikusen0335,

In case you haven't already included Disqus, I updated the template to do so. See the README

**Comment by rikusen0335** [comment]
Thanks! And sorry but I didn't have some free time :(
