### ISSUE TITLE
Disable Night Mode via Settings

### ISSUE THREAD

**Issue by filipre** [onweru/newsroom#20]
Hi, 

Thank you for the theme. It looks very good. I love the light theme but do not really like the dark version of it. Also, the toggle button does not work because the following code is throwing an error: "images is not an function". I don't need lazy loading so this is fine.

```js
  (function lazyLoadImages() {
    const images = elems('img');
    images.forEach(function(image){
      // supported natively by most modern browsers. 
      image.loading = "lazy";
    });
 })();
```

I wonder, is there a way to get completely rid of the dark mode? I would like to enforce the light theme. I tried to comment out several parts of the js code but for some reason, it still shows the dark theme. Is there maybe an option to enable/disable the "automatic" detection?

Best
René

**Comment by onweru** [comment]
Hi Rene,

Thanks for your feedback. I like your suggestion, I will explore it in the coming days.

Thanks,
Weru.

**Comment by visheratin** [comment]
The fix for the mentioned error is in PR #21.

**Comment by visheratin** [comment]
And regarding the question itself, I made a [minor change](https://github.com/visheratin/newsroom/commit/60bba875dfd277a57cff49083cb04d912a208fce) that allows disabling dark theme in the config file.
```
[params]
  disableDark = "false"
```
If @onweru wants, I can PR these changes.

**Comment by onweru** [comment]
Thanks for contributing @visheratin. The images conditional is perfect. I will build on top of the dark mode fix. Thanks once again.

**Comment by visheratin** [comment]
You are very welcome!
