### ISSUE TITLE
[Question] How to enable dark mode?

### ISSUE THREAD

**Issue by Silipwn** [onweru/newsroom#3]
How to do we enable dark mode in the theme?

**Comment by onweru** [comment]
@Silipwn, for now the dark mode is automatic. If you enable  dark mode on your system, the site automatically adapt to dark mode. At least if your os and browser allows it.

In the coming week, I will roll out a ui control so that users can choose to opt in or out of dark mode.

**Comment by Silipwn** [comment]
Sounds great :smile:

**Comment by onweru** [comment]
@Silipwn, I added a UI control as promised. It's embedded on the menu ... [see the demo here](https://rooms.netlify.com/). It works perfectly on Chrome. I disabled it temporarily in the last commit [in this line](https://github.com/onweru/newsroom/blob/91f2357b4a2247570e63e35797105acddabe0ff5/assets/scss/_components.scss#L222). 

I will explore the reasons why the solution doesn't seem to work properly outside of chrome.
