### ISSUE TITLE
Cant make this theme work: theme is not getting rendered correctly

### ISSUE THREAD

**Issue by soumya997** [onweru/newsroom#30]
Hi, @onweru this theme is really great and I want to use it, but after using `hugo server -D` the website that I am getting in the localhost that is looking something like this,
<br>
![Screenshot (1218)](https://user-images.githubusercontent.com/54326088/120295712-0610dd80-c2e5-11eb-8703-bfd46f7c2ce9.png)
<be>
where it should look like this(https://themes.gohugo.io/theme/newsroom/),
<br>
![Screenshot (1219)](https://user-images.githubusercontent.com/54326088/120295807-20e35200-c2e5-11eb-8842-36d2c7f64504.png) .

The steps that I followed,
1. `hugo new site blog1`
2.  `cd blog1`
3.  `git init`
4.  `git submodule add https://github.com/onweru/newsroom.git themes/newsroom`
5.  Then copy-pasted all the files and folders that were present in the exampleSite folder. 
6.  made `baseurl = ""` 
7. ran the command `hugo server -D`

I am using windows 10,
`hugo version` gives me `hugo v0.82.0-9D960784 windows/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio`

It will be very helpful if you can help. thank you.

**Comment by onweru** [comment]
@soumya997, please include a trailing slash as commented on this line https://github.com/onweru/newsroom/blob/7c332200b78b25a2b7891011a33fcacecf86fa80/exampleSite/config.toml#L1

**Comment by soumya997** [comment]
> @soumya997, please include a trailing slash as commented on this line
> 
> https://github.com/onweru/newsroom/blob/7c332200b78b25a2b7891011a33fcacecf86fa80/exampleSite/config.toml#L1

Yeah @onweru  I have changed the `baseurl`, and added `"https://example.com/"` in there, but it is still showing the same thing, it was unable to render the theme correctly.

**Comment by soumya997** [comment]
@onweru I just tried with the latest version of hugo, but the outcome is the same😭.

**Comment by onweru** [comment]
@soumya997, unless you're hosting on https://example.com/, that will not work. Please use the URL where you are hosting on.

**Comment by soumya997** [comment]
@onweru I am hosing on the localhost for testing purposes, But the site is not loading properly.

**Comment by onweru** [comment]
> I am using windows 10,
hugo version gives me hugo v0.82.0-9D960784 windows/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio

I missed this 👆🏼 from your earlier response.  Please ensure you have Hugo extended installed. You seem to be using the normal version of Hugo which wouldn't work. I would recommend installing Hugo using `chocolatey` on windows

https://gohugo.io/getting-started/installing/#chocolatey-windows

Alternatively, you can grab the [extended version of hugo executable here]( https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_extended_0.83.1_Windows-64bit.zip)

**Comment by soumya997** [comment]
I knew you @onweru can help me out with this, thank you so much🙇‍♂️. It is working now.
