### ISSUE TITLE
Typo in OpenGraph.html Should be "post"

### ISSUE THREAD

**Issue by MatthewMcD** [onweru/newsroom#45]
Love this theme, while tweaking my site for things like Keywords, Description, and Twitter Card handling, I noticed that the Twitter Card never works. Then I spotted this in `opengraph.html`:
```markdown
{{- if eq .Section "blog" -}}
```

it should read:
```markdown
{{- if eq .Section "post" -}}
```
for the example site.

Also, @onweru I have updated the description handling to default to using the frontmatter and the keywords to using the post tags. My implementation may be specific to my case but if you want me to send a PR for them I can. Just let me know.

**Comment by saligrama** [comment]
@onweru found another typo in opengraph.html: line 16

```{{- with .Params.image }}```

should be

```{{- with $params.image }}```

**Comment by onweru** [comment]
@saligrama, thanks for informing me of this bug.

> found another typo in opengraph.html: line 16

Not quite, the `.Params` was referring to the page levels parameters object while `$params` were referring to params under config.toml file. I have change `params` to `$config` to avoid the confusion.

`$params` my exist on other templates. A refactor for another time 😛
