### ISSUE TITLE
Home page: Number of articles

### ISSUE THREAD

**Issue by jchrom** [onweru/newsroom#5]
Nice theme work @onweru !

Can you please advise:

I'd like to change the number of articles that appear on the home page. Can you please point me in the right direction? Feel free to link relevant Hugo docs if that's easier, I just need a starting point.

Much appreciated!

**Comment by onweru** [comment]
@jchrom, glad you like the theme. Change the number of articles showing on home page through the config.toml. See the [the relevant line from config.toml](https://github.com/onweru/newsroom/blob/48868918ce57481cf6edbd5849b407f24cbdf326/exampleSite/config.toml#L7)

**Comment by jchrom** [comment]
Huh, makes sense! Guess I thought that'd be too easy. Thanks!
