### ISSUE TITLE
SASS issues on Android?

### ISSUE THREAD

**Issue by LarsDu** [onweru/newsroom#54]
I noticed that my test page https://dogames.org does not load on my android device.
I think it has to do something with the sass layout files?
Is there some sort of prerequisite needed to get the site to render properly?

**Comment by onweru** [comment]
By the time you publish your site, the sass files are already compiled to basic CSS. If your site doesn't load on android, I have no idea what is up. Am  no5 an android user so I cannot reproduce

**Comment by LarsDu** [comment]
This looks to be a security issue that crops up on certain builds. Closing the issue for now. Interestingly enough, I attempted to change the "Cookie font" of the nav bar
https://github.com/LarsDu/newsroom-gamedev/blob/master/assets/sass/_variables.sass
https://github.com/LarsDu/newsroom-gamedev/blob/master/assets/sass/_fonts.sass#L56
but it looks like custom fonts don't load?

**Comment by LarsDu** [comment]
Ok for future reference:
- I'm using cloudflare CDNs which have an option to compress css and javascript files. On certain browsers, this will lead to a SHA256 mismatch (some sort of security setting) which will disable the css. Disabling compression on Cloudflare fixes it
- Switching the replacement font from TTF to WOFF seemed to make custom fonts work just fine.
