### ISSUE TITLE
Non-italic font

### ISSUE THREAD

**Issue by DazWilkin** [onweru/newsroom#67]
Thanks for creating this theme!

Is there a way to stop the site title from being rendered as an italic font?

The remaining page content appears to use a modern font that would be ideal for the tile too.

**Comment by onweru** [comment]
@DazWilkin, you can override this line https://github.com/onweru/newsroom/blob/c9821ac4124e074b67473be562587efa1649c7ef/assets/sass/_nav.sass#L64

**Comment by DazWilkin** [comment]
Awesome! Thank you very much!
