### ISSUE TITLE
Mobile Dark theme not working

### ISSUE THREAD

**Issue by wesleymutwiri** [onweru/newsroom#9]
I currently have my blog using the newsroom theme but the toggle button isn't working only for the mobile version of the site. The site on a normal browser works perfectly. Would highly appreciate any assistance provided.

**Comment by onweru** [comment]
@wesleymutwiri, on what device are you viewing on? please include ios / android version ... including the browser. FYI, it will not work on browsers that are [not currently supported]( https://caniuse.com/#search=refers-color-scheme). I have tested on ios and everything looks good.

**Comment by wesleymutwiri** [comment]
I'm using android 8.1 firefox. I think the issue is my configuration but I'm not really sure...
Any advice you can give on how to setup the application better?

**Comment by onweru** [comment]
Could I see your repo? Also, have you tested on other browsers?

**Comment by wesleymutwiri** [comment]
The repo is private but I can add you as a collaborator. I've tested it on Chrome and it works perfectly fine. Not sure if it's an issue with my code

**Comment by onweru** [comment]
Ah, in that case, it's most likely an issue with the browser.
